# Generated by Django 5.0.4 on 2024-10-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="image",
            field=models.ImageField(default=False, upload_to="image"),
        ),
    ]
