# Generated by Django 5.0.4 on 2024-10-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_clients_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clients",
            old_name="image",
            new_name="logo",
        ),
        migrations.AddField(
            model_name="clients",
            name="dept",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clients",
            name="validation_no",
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
