# Generated by Django 5.0.4 on 2024-10-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_rename_image_clients_logo_clients_dept_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="client",
            field=models.CharField(max_length=150),
        ),
    ]
